### ISSUE TITLE
Ensure `BaseURL` is absolute

### ISSUE THREAD

**Issue by allevo** [davidebianchi/go-jsonclient#3]
if `BaseURL` is relatve, which is the behaviour?

In order not to reply this question, `New` may return error if `BaseURL` is not an absolute url.

The check I suppose to be implemented are:
- absolute url
- the scheme are `http` or `https` (can other scheme make sense?)

If you want, l'll prepare a PR for that checks

**Comment by davidebianchi** [comment]
Good point! It's a good idea to add checks on the `New` function.
Under the hood we use the `net/http` package, so the only supported schemes should be http and https when a request is executed, and the `Do` function ensure

It would be great to have a PR to implement it!

**Comment by allevo** [comment]
I'll!

But I have to change this test (ie it is a breaking change):
https://github.com/davidebianchi/go-jsonclient/blob/cf85950992413b1a38027833e1ade91d3045e2fb/main_test.go#L41-L53

Is it a problem?

**Comment by davidebianchi** [comment]
Check may be done if options.BaseURL is different from empty string?

I would not do a breaking changes for now. It could be useful to use the client without a base url, adding only some base headers for example.

Without a base url, when a new request is created it is possible to pass a complete absolute url

**Comment by allevo** [comment]
Truly we have to check:
- the BaseURL if provided
- if not provided, `strURL` has to be absolute
- if provided, `strURL` has not to be absolute

Have I understood correctly?

**Comment by davidebianchi** [comment]
Yes, correct!
For the third case, `strURL` has not to be absolute and should not start with slash.
This because otherwise the url concat does not works as expected by the user.

In this playground I added some url concat examples. The only working correctly it's the first:
https://play.golang.org/p/fliCReZO49q
